 - 5432
    image: "postgres:9.6.23"
    networks:
      - servian
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
  frontend:
    command: serve
    container_name: servianserveapp
    depends_on:
      - migration
    environment:
      - VTT_DBUSER=saadmin
      - VTT_DBPASSWORD=Mohan@143
      - VTT_DBNAME=serviandb
      - VTT_DBPORT=5432
      - VTT_DBHOST=db
      - VTT_LISTENHOST=frontend
      - VTT_LISTENPORT=3000
    image: "servian/techchallengeapp:latest"
    networks:
      - servian
    ports:
      - "3000:3000"
    restart: always
  migration:
    command: updatedb
    container_name: servianupdatedb
    depends_on:
      - db
    environment:
      - VTT_DBUSER=saadmin
      - VTT_DBPASSWORD=Mohan@143
      - VTT_DBNAME=serviandb
      - VTT_DBPORT=5432
      - VTT_DBHOST=db
    image: "servian/techchallengeapp:latest"
    networks:
      - servian
volumes:
  db-data:
